Pull request 1848: fix-snap
Merge in DNS/adguard-home from fix-snap to master

Squashed commit of the following:

commit 4a12b2709229150e1b896b71b2b0a99249f94fde
Author: Ainar Garipov <A.Garipov@AdGuard.COM>
Date:   Sat May 20 11:51:25 2023 +0300

    bamboo-specs: upd snap script

diff --git a/bamboo-specs/release.yaml b/bamboo-specs/release.yaml
--- a/bamboo-specs/release.yaml
+++ b/bamboo-specs/release.yaml
@@ -232,25 +232,24 @@
         case "$channel"
         in
         ('release')
-              snapchannel='candidate'
-              ;;
+                snapchannel='candidate'
+                ;;
         ('beta')
-              snapchannel='beta'
-              ;;
+                snapchannel='beta'
+                ;;
         ('edge')
-              snapchannel='edge'
-              ;;
+                snapchannel='edge'
+                ;;
         (*)
-              echo "invalid channel '$channel'"
-              exit 1
-              ;;
+                echo "invalid channel '$channel'"
+                exit 1
+                ;;
         esac
 
         env\
                 SNAPCRAFT_CHANNEL="$snapchannel"\
                 SNAPCRAFT_EMAIL="${bamboo.snapcraftEmail}"\
-                SNAPCRAFT_MACAROON="${bamboo.snapcraftMacaroonPassword}"\
-                SNAPCRAFT_UBUNTU_DISCHARGE="${bamboo.snapcraftUbuntuDischargePassword}"\
+                SNAPCRAFT_STORE_CREDENTIALS="${bamboo.snapcraftMacaroonPassword}"\
                 ../bamboo-deploy-publisher/deploy.sh adguard-home-snap
   'final-tasks':
   - 'clean'
@@ -280,9 +279,9 @@
 
         if [ "$channel" != 'release' ] && [ "${channel}" != 'beta' ]
         then
-              echo "don't publish to GitHub Releases for this channel"
+                echo "don't publish to GitHub Releases for this channel"
 
-              exit 0
+                exit 0
         fi
 
         cd ./dist/
