Pull request: all: imp hacking, hooks
Merge in DNS/adguard-home from imp-hacking to master

Squashed commit of the following:

commit fcc0740526948256b5b356a3a7969e00baa35ff7
Author: Ainar Garipov <A.Garipov@AdGuard.COM>
Date:   Mon Jun 28 18:16:57 2021 +0300

    all: imp hacking, hooks

diff --git a/scripts/hooks/pre-commit b/scripts/hooks/pre-commit
--- a/scripts/hooks/pre-commit
+++ b/scripts/hooks/pre-commit
@@ -2,6 +2,10 @@
 
 set -e -f -u
 
+# Show all temporary todos to the programmer but don't fail the commit
+# if there are any, because the commit could be in a temporary branch.
+git grep -e 'TODO.*!!' -- ':!HACKING.md' ':!scripts/hooks/pre-commit' | more || :
+
 if [ "$( git diff --cached --name-only -- 'client/*.js' )" ]
 then
 	make js-lint js-test
